import type { Metadata } from "next";
import { Kaushan_Script, Poiret_One } from "next/font/google";
import { Footer } from "./components/footer/Footer";
import { Header } from "./components/header/Header";
import "./globals.css";

const poiret = Poiret_One({
  weight: "400",
  subsets: ["latin"],
});

const kaushan = Kaushan_Script({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poiret.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
